---
title: 'New Year Accident Data'
output: 
  html_document:
    toc: true # table of content true
    toc_float: true
    depth: 3  # upto three depths of headings (specified by #, ## and ###)
    number_sections: true  ## if you want number sections at each table header
    theme: readable  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,warning=FALSE,message=FALSE)
```

```{r load data, results='hide'}
les_packages <- lapply(c("ade4","caret","tidyverse","ggthemes","DT","data.table","dplyr"), 
                       require, character.only = TRUE)

## load files
input_path <- '../data/'
query_festival = fread(paste0(input_path,'query_festival.csv'))
#query_festival[is.na(query_festival)] = 'unknown'
#query_festival$age = sapply(query_festival$age,FUN=function(x) ifelse(x=='unknown',NA,x))
df = query_festival[complete.cases(query_festival),] %>% 
  mutate(ISO = as.character(ISO),
         death_flag = ifelse(result=='cured',0,1),
         buckle_flag = ifelse(belt=='no',0,1),
         age = as.numeric(age),
         time = gsub('[^[:alnum:] ]','',time)) %>%
  select(-hospital_code,-result)
df = df[complete.cases(df),]

#recode
# query_festival = query_festival %>% mutate(
#   age = ifelse(age==99|age==0,NA,age),
#   reporter = ifelse(reporter=='????????????????????','dead_at_site',reporter),
#   `Refer-Admit` = ifelse(`Refer-Admit`=='?????????? admit','admit_refer',`Refer-Admit`)
# )
# names(query_festival) = c('year', 'ISO', 'hospital_code', 'date', 'time', 'sex', 'age', 'location', 'patient_status', 'vehicle_1', 'vehicle_2', 'belt', 'drinking', 'reporter', 'referral_flag', 'result', 'days')
# write.csv(query_festival,paste0(input_path,'query_festival.csv'))
```

# Exploration

## Time of Day

```{r}
tod = df %>% group_by(time) %>% summarise(nb_cases = n(), nb_deaths = sum(death_flag),
            avg_deaths = mean(death_flag), avg_days=mean(days))
write.csv(tod,paste0(input_path,'tod.csv'))
```

### Number of Accidents

```{r}
g = ggplot(tod,aes(x=substr(time,1,2),y=nb_cases)) + geom_bar(stat='identity') +
  theme_fivethirtyeight() + scale_fill_wsj() +
  geom_hline(tod,yintercept = mean(tod$nb_cases),color='red',size=1)
g
```

### Chance of Death

```{r}
g = ggplot(tod,aes(x=substr(time,1,2),y=avg_deaths)) + geom_bar(stat='identity') +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight() + scale_fill_wsj()+
  geom_hline(tod,yintercept = sum(tod$nb_deaths) / sum(tod$nb_cases),color='red',size=1)
g
```


## Driving Under Influence

### Chance of Death

```{r}
dui = df %>% group_by(drinking) %>% 
  summarise(nb_cases = n(), nb_deaths = sum(death_flag),
            avg_deaths = mean(death_flag))
prop.test(dui$nb_deaths,dui$nb_cases,alternative = 'two.sided')
g= ggplot(dui,aes(x=drinking,y=avg_deaths,fill=drinking))+ geom_bar(stat='identity') +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight() + scale_fill_wsj() +
  geom_text(aes(x=drinking,y=avg_deaths+0.001,
                label=paste0(round(100*avg_deaths,2),'%')))
g
```


```{r}
dui_cases = df %>% 
  group_by(vehicle_1,drinking) %>% 
  summarise(nb_cases=n()) %>% spread(drinking,nb_cases) %>%
  rename(nb_cases_0=`n`,nb_cases_1 = `y`) %>% na.omit
dui_deaths = df %>% 
  group_by(vehicle_1,drinking) %>% 
  summarise(nb_deaths = sum(death_flag)) %>% spread(drinking,nb_deaths) %>%
  rename(nb_deaths_0=`n`,nb_deaths_1 = `y`) %>% na.omit

dui_vehicle = dui_cases %>% inner_join(dui_deaths) %>%
  mutate(avg_deaths_0 = nb_deaths_0 / nb_cases_0,
         avg_deaths_1 = nb_deaths_1 / nb_cases_1,
         p = mapply(function(x1,x2,n1,n2) 
           prop.test(c(x1,x2),c(n1,n2),alternative = 'two.sided')$p.value,
                    nb_deaths_0,nb_deaths_1,nb_cases_0,nb_cases_1),
         p = round(p,2)) %>% filter(nb_cases_0 > 500 & nb_cases_1 > 500)

write.csv(dui_vehicle,paste0(input_path,'dui_vehicle_deaths.csv'))

dui_m = dui_vehicle %>% select(vehicle_1,avg_deaths_0,avg_deaths_1) %>%
  rename(no_drink=avg_deaths_0,drink=avg_deaths_1)  %>%
  melt(id.vars='vehicle_1')

g = ggplot(dui_m,aes(x=vehicle_1,y=value,fill=variable)) + 
  geom_bar(stat='identity',position='dodge') +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight() + scale_fill_wsj() 
g
```

### Recovery Period

```{r}
dui = df %>% group_by(drinking) %>% 
  summarise(nb_cases = n(), nb_days = sum(days),
            avg_days = mean(days))
t.test(df[df$drinking=='n',]$days,df[df$drinking=='y',]$days)

g = ggplot(dui,aes(x=drinking,y=avg_days,fill=drinking))+ geom_bar(stat='identity') +
  theme_fivethirtyeight() + scale_fill_wsj() +
  geom_text(aes(x=drinking,y=avg_days+0.05,
                label=paste0(round(avg_days,2),' days')))
g
```


```{r}
dui_cases = df %>% 
  group_by(vehicle_1,drinking) %>% 
  summarise(nb_cases=n()) %>% spread(drinking,nb_cases) %>%
  rename(nb_cases_0=`n`,nb_cases_1 = `y`) %>% na.omit
dui_days = df %>% 
  group_by(vehicle_1,drinking) %>% 
  summarise(nb_days = sum(days)) %>% spread(drinking,nb_days) %>%
  rename(nb_days_0=`n`,nb_days_1 = `y`) %>% na.omit

dui_vehicle = dui_cases %>% inner_join(dui_days) %>%
  mutate(avg_days_0 = nb_days_0 / nb_cases_0,
         avg_days_1 = nb_days_1 / nb_cases_1,
         p = mapply(function(x1,x2,n1,n2) 
           prop.test(c(x1,x2),c(n1,n2),alternative = 'two.sided')$p.value,
                    nb_days_0,nb_days_1,nb_cases_0,nb_cases_1),
         p = round(p,2)) %>% filter(nb_cases_0 > 500 & nb_cases_1 > 500)

write.csv(dui_vehicle,paste0(input_path,'dui_vehicle_days.csv'))

dui_m = dui_vehicle %>% select(vehicle_1,avg_days_0,avg_days_1) %>%
  rename(no_drink=avg_days_0,drink=avg_days_1)  %>%
  melt(id.vars='vehicle_1')

g = ggplot(dui_m,aes(x=vehicle_1,y=value,fill=variable)) + 
  geom_bar(stat='identity',position='dodge') +
  theme_fivethirtyeight() + scale_fill_wsj() 
g
```
## Buckle Up

### Chance of Death

```{r}
df$buckle_flag = as.factor(df$buckle_flag)
buckle = df %>% group_by(buckle_flag) %>% 
  summarise(nb_cases = n(), nb_deaths = sum(death_flag),
            avg_deaths = mean(death_flag))
prop.test(buckle$nb_deaths,buckle$nb_cases,alternative = 'two.sided')
g= ggplot(buckle,aes(x=buckle_flag,y=avg_deaths,fill=buckle_flag))+ geom_bar(stat='identity') +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight() + scale_fill_wsj() +
  geom_text(aes(x=buckle_flag,y=avg_deaths+0.001,
                label=paste0(round(100*avg_deaths,2),'%')))
g
```


```{r}
buckle_cases = df %>% 
  group_by(vehicle_1,buckle_flag) %>% 
  summarise(nb_cases=n()) %>% spread(buckle_flag,nb_cases) %>%
  rename(nb_cases_0=`0`,nb_cases_1 = `1`) %>% na.omit
buckle_deaths = df %>% 
  group_by(vehicle_1,buckle_flag) %>% 
  summarise(nb_deaths = sum(death_flag)) %>% spread(buckle_flag,nb_deaths) %>%
  rename(nb_deaths_0=`0`,nb_deaths_1 = `1`) %>% na.omit

buckle_vehicle = buckle_cases %>% inner_join(buckle_deaths) %>%
  mutate(avg_deaths_0 = nb_deaths_0 / nb_cases_0,
         avg_deaths_1 = nb_deaths_1 / nb_cases_1,
         p = mapply(function(x1,x2,n1,n2) 
           prop.test(c(x1,x2),c(n1,n2),alternative = 'two.sided')$p.value,
                    nb_deaths_0,nb_deaths_1,nb_cases_0,nb_cases_1),
         p = round(p,2)) %>% filter(nb_cases_0 > 500 & nb_cases_1 > 500)

write.csv(buckle_vehicle,paste0(input_path,'buckle_vehicle_deaths.csv'))

buckle_m = buckle_vehicle %>% select(vehicle_1,avg_deaths_0,avg_deaths_1) %>%
  rename(no_buckle=avg_deaths_0,buckle=avg_deaths_1)  %>%
  melt(id.vars='vehicle_1')

g = ggplot(buckle_m,aes(x=vehicle_1,y=value,fill=variable)) + 
  geom_bar(stat='identity',position='dodge') +
  scale_y_continuous(labels = scales::percent) +
  theme_fivethirtyeight() + scale_fill_wsj() 
g
```

### Recovery Period

```{r}
buckle = df %>% group_by(buckle_flag) %>% 
  summarise(nb_cases = n(), nb_days = sum(days),
            avg_days = mean(days))
t.test(df[df$buckle_flag=='0',]$days,df[df$buckle_flag=='1',]$days)

g = ggplot(buckle,aes(x=buckle_flag,y=avg_days,fill=buckle_flag))+ geom_bar(stat='identity') +
  theme_fivethirtyeight() + scale_fill_wsj() +
  geom_text(aes(x=buckle_flag,y=avg_days+0.05,
                label=paste0(round(avg_days,2),' days')))
g
```


```{r}
buckle_cases = df %>% 
  group_by(vehicle_1,buckle_flag) %>% 
  summarise(nb_cases=n()) %>% spread(buckle_flag,nb_cases) %>%
  rename(nb_cases_0=`0`,nb_cases_1 = `1`) %>% na.omit
buckle_days = df %>% 
  group_by(vehicle_1,buckle_flag) %>% 
  summarise(nb_days = sum(days)) %>% spread(buckle_flag,nb_days) %>%
  rename(nb_days_0=`0`,nb_days_1 = `1`) %>% na.omit

buckle_vehicle = buckle_cases %>% inner_join(buckle_days) %>%
  mutate(avg_days_0 = nb_days_0 / nb_cases_0,
         avg_days_1 = nb_days_1 / nb_cases_1,
         p = mapply(function(x1,x2,n1,n2) 
           prop.test(c(x1,x2),c(n1,n2),alternative = 'two.sided')$p.value,
                    nb_days_0,nb_days_1,nb_cases_0,nb_cases_1),
         p = round(p,2)) %>% filter(nb_cases_0 > 500 & nb_cases_1 > 500)

write.csv(buckle_vehicle,paste0(input_path,'buckle_vehicle_days.csv'))

buckle_m = buckle_vehicle %>% select(vehicle_1,avg_days_0,avg_days_1) %>%
  rename(no_buckle=avg_days_0,buckle=avg_days_1)  %>%
  melt(id.vars='vehicle_1')

g = ggplot(buckle_m,aes(x=vehicle_1,y=value,fill=variable)) + 
  geom_bar(stat='identity',position='dodge') +
  theme_fivethirtyeight() + scale_fill_wsj() 
g
```
